spring.application.name=study-tracker-auth

# --- Database ---
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/study_tracker}
spring.datasource.username=${DB_USER:study}
spring.datasource.password=${DB_PASSWORD:change-me}

spring.jpa.properties.hibernate.default_schema=auth
spring.liquibase.default-schema=auth
spring.liquibase.liquibase-schema=auth

spring.jpa.hibernate.ddl-auto=validate
